services:
  caqes-core:
    build:
      context: .
      dockerfile: caqes-core.Dockerfile
    container_name: core
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - mosquitto

  syslog-ng:
    build:
      context: .
      dockerfile: syslog-ng.Dockerfile
    container_name: syslog-ng
    volumes:
      - syslog-config:/etc/syslog-ng
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - mosquitto-config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883" # Default MQTT port
      - "9001:9001" # WebSocket port (optional, if needed)
    restart: unless-stopped

volumes:
  syslog-config:
  mosquitto-config:
  mosquitto-data:
  mosquitto-log:
