services:
  caqes-core:
    build:
      context: .
      dockerfile: caqes-core.Dockerfile
    container_name: core
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - nats
  syslog-ng:
    build:
      context: .
      dockerfile: syslog-ng.Dockerfile
    container_name: syslog-ng
    volumes:
      - syslog-config:/etc/syslog-ng
    ports:
      - "514:514/udp"
      - "601:601/tcp"

  nats:
    image: nats:latest
    container_name: nats
    volumes:
      - nats-config:/etc/nats
      - nats-data:/data/jetstream
    command: "-c /etc/nats/nats-server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

volumes:
  nats-data:
  nats-config:
  syslog-config:
