services:
  caqes-core:
    build:
      context: .
      dockerfile: caqes-core.Dockerfile
    container_name: caqes-core
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - mosquitto

  syslog-ng:
    build:
      context: .
      dockerfile: syslog-ng.Dockerfile
    container_name: syslog-ng
    volumes:
      - ./config/syslog-ng:/etc/syslog-ng
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - emqx-data:/opt/emqx/data

volumes:
  mosquitto-data:
  mosquitto-log:
  emqx-data:
