services:
  caqes-core:
    build:
      context: .
      dockerfile: caqes-core.Dockerfile
    container_name: core
    volumes:
      - ..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - mosquitto

  syslog-ng:
    build:
      context: .
      dockerfile: syslog-ng.Dockerfile
    container_name: syslog-ng
    volumes:
      - ../config/syslog-ng:/etc/syslog-ng # Mount local config directory
    ports:
      - "514:514/udp"
      - "601:601/tcp"
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - ../config/mosquitto:/mosquitto/config # Mount local config directory
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883" # Default MQTT port
      - "9001:9001" # WebSocket port (optional, if needed)

volumes:
  mosquitto-data:
  mosquitto-log:
